version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongo
    environment:
      - RUN_MODE=local

  mongo:
    image: mongo:3.6
    ports: 
      - 27017:27017
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - API_URL=server:3000/api
